set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports j]
set_property IOSTANDARD LVCMOS33 [get_ports k]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports qbar]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T1 [get_ports j]
set_property PACKAGE_PIN U1 [get_ports k]
set_property PACKAGE_PIN U3 [get_ports qbar]
set_property PACKAGE_PIN P3 [get_ports q]

